Keep location_base on update if no baseurl defined in args
rpm-software-management/createrepo_c pull request #326
Opened 2022-08-30 08:13 UTC by achamo

When using --update, --skip-stat and --reycle-pkglist we do not want to rewrite location_base but keep all the metadata for a package
By default createrepo_c removes the location_base that was already set in the metadata using the null value from the parameter
Skip it and keep the location_base when it's null (and if both are null it shouldn't change the current behaviour)

2022-09-30 21:53 UTC, dralley commented
Do you think putting this:

```C
} else {
    location_base = pkg->location_base;
}
```

on line 430 might be more appropriate?

2022-09-30 21:54 UTC, dralley commented on src/dumper_thread.c
>                  // packages in old metadata.
The comment could use updating

2023-02-09 06:47 UTC, kontura requested changes
Hello, sorry for the delay.
The change looks good, it does affect all runs with `--update` not just with `--skip-stat` but I think that is fine.

I have tried to resolve the conflicts but it created a new commit and its not ideal. 
If you are still interested can you rebase this?

2023-04-12 15:55 UTC, achamo commented
Thanks for the update, I'm still interested as I'm using it to generate my repositories! I would prefer to see this patch merged than keep maintaining my own branch.
I updated the comment in the code, as suggested!

2023-04-17 06:31 UTC, kontura commented
Thanks!

2023-04-17 06:31 UTC, merged