Avoid delta regeneration if drpm exists and target_md5 matches
rpm-software-management/createrepo_c pull request #334
Opened 2023-01-06 10:20 UTC by davidvoit

If a drpm file for the same target already exists, we don't need to process the original files again.

We can't check the source rpm only the target rpm hashsum, but as drpm is content based not rpm based this should be could enough.

If the target is overridden with different content but has the same name, we need to recalculate the delta rpm.

2023-02-09 08:32 UTC, kontura requested changes
Hello, I don't really like sneaking the `MD5` hash back in like this.
I think we should either enable this only when the `LEGACY_HASHES` are allowed or find a different way.

2023-02-09 08:32 UTC, kontura commented on src/deltarpms.c
> +cr_drpm_check_checksum(const char *drpmpath, const char *new_path) {
I think `target_md5` and `delta` could leak in the error cases.

2023-02-09 08:48 UTC, davidvoit commented
MD5 drpms Always are using md5 sums even iegacy is disabled. So you only
break the caching then but producing drpm still works this seems odd to me

Maybe drpm should be updated If we really want to phase out md5

amatej ***@***.***> schrieb am Do., 9. Feb. 2023, 09:32:

> ***@***.**** requested changes on this pull request.
>
> Hello, I don't really like sneaking the MD5 hash back in like this.
> I think we should either enable this only when the LEGACY_HASHES are
> allowed or find a different way.
> ------------------------------
>
> In src/deltarpms.c
> <https://github.com/rpm-software-management/createrepo_c/pull/334#discussion_r1101117276>
> :
>
> > +        return FALSE;
> +    }
> +
> +    error = drpm_get_string(delta, DRPM_TAG_TGTMD5, &target_md5);
> +
> +    if (error != DRPM_ERR_OK) {
> +        return FALSE;
> +    }
> +
> +    error = drpm_destroy(&delta);
> +
> +    if (error != DRPM_ERR_OK) {
> +        return FALSE;
> +    }
> +
> +    checksum = cr_checksum_file(new_path, CR_CHECKSUM_MD5INT, &tmp_err);
>
> This checksum is also leaked.
> ------------------------------
>
> In src/deltarpms.c
> <https://github.com/rpm-software-management/createrepo_c/pull/334#discussion_r1101120751>
> :
>
> > @@ -49,6 +50,43 @@ cr_drpm_support(void)
>
>  #ifdef    CR_DELTA_RPM_SUPPORT
>
> +gboolean
> +cr_drpm_check_checksum(const char *drpmpath, const char *new_path) {
>
> I think target_md5 and delta could leak in the error cases.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rpm-software-management/createrepo_c/pull/334#pullrequestreview-1290626329>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAADDHTY6RWZIUNOFYFBPSDWWSTRTANCNFSM6AAAAAATS5V4NQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-02-09 10:27 UTC, kontura commented
> Maybe drpm should be updated If we really want to phase out md5

Yes, if possible that would be the best option.

Also if this functionality was directly in drpm createrepo_c wouldn't need to anything about the used hash.

2023-10-25 08:23 UTC, kontura commented
I am closing this PR, since this is not the right place to add it.

If you are still interested in the feature please add it to [drpm](https://github.com/rpm-software-management/drpm) (probably in `drpm_make`(...)).

2023-10-25 08:23 UTC, closed without merging