Unify groupfile handling with other metadata types
rpm-software-management/createrepo_c pull request #373
Opened 2023-06-15 12:38 UTC by kontura

Create just "group" repomd record, no compression suffix. Do not include uncompressed groupfile in metadata.

Additionally it is now possible to specify compressed groupfile as the input.

This is for: https://fedoraproject.org/wiki/Changes/createrepo_c_1.0.0

2023-06-15 12:41 UTC, kontura commented
Test update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1320

2023-07-18 07:12 UTC, Conan-Kudo approved these changes

2023-07-18 07:14 UTC, Conan-Kudo requested changes
All the groupfile integration tests are failing. Is it because we no longer produce an uncompressed group file?

2023-07-18 07:17 UTC, kontura commented
> All the groupfile integration tests are failing. Is it because we no longer produce an uncompressed group file?

yes, the tests need to be updated, I made PRs, links in https://github.com/rpm-software-management/createrepo_c/pull/373#issuecomment-1592970881.

2023-07-18 07:19 UTC, Conan-Kudo approved these changes

2023-07-18 07:23 UTC, merged