Use compatibility for createrepo
rpm-software-management/createrepo_c pull request #420
Opened 2024-02-07 21:16 UTC by kwizart

Reported as #403

The point of using createrepo is to keep the same behavior with the createrepo command. Users that want modern behavior should use createrepo_c command instead.

2024-02-07 21:17 UTC, kwizart commented
Tested on my side with this koji scratch build for fedora rawhide
https://koji.fedoraproject.org/koji/taskinfo?taskID=113132488

2024-02-08 01:29 UTC, Conan-Kudo requested changes
I would rather not have this. Tools should adjust accordingly instead.

2024-02-08 08:24 UTC, kwizart commented
Do you have a particular reason why you want to change every dependent software instead ?
And can you also include what's the point to keep different commands createrepo and createrepo_c if they have the same behavior ?

2024-02-08 13:04 UTC, Conan-Kudo commented
Ideally, we wouldn't produce the `_c` binaries anymore. There's no point to them anymore since the old py-createrepo is gone.

2024-02-08 14:44 UTC, kwizart commented
Well, I'm just exactly raising a point for a createrepo use over createrepo_c.

2024-09-25 18:13 UTC, dralley commented
IMO, this doesn't feel particularly worthwhile at this point

2024-10-03 10:48 UTC, kontura commented
Right, there is the `--compatibility` flag.

2024-10-03 10:48 UTC, closed without merging